apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "k8s-ip" # gcpì˜ static ip
    networking.gke.io/v1beta1.FrontendConfig: "https-redirect"

spec:
  tls:
    - hosts: 
      - www.mymincloud.com
      secretName: tls-crt
  rules:
  - host: www.mymincloud.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mynginx
            port: 
              number: 80